### ISSUE TITLE
Stuck on block 61454

### ISSUE THREAD

**Issue by gooooba** [ProjectIxian/Ixian-source#1]
Tried to start with -c, but it is the same or the last day...

> 2018-11-22 06:43:51.7267|info|Thread(11): Creating a WalletState snapshot.
> 2018-11-22 06:43:51.7807|info|Thread(11): Reverting WalletState snapshot (11 wallets).
> 2018-11-22 06:43:51.7807|info|Thread(11): VerifyBlock duration: 65,4597ms
> 2018-11-22 06:43:51.7807|warn|Thread(11): Received block #61454 (1513d3c68ffd687ea19120a7bc75220a64b1ce6bc99b7f9866472cb0f29b524a) which had a signature that wasn't found in the PL!
> 2018-11-22 06:43:51.7807|info|Thread(11): This is the block we are currently working on. Merging signatures.
> 2018-11-22 06:43:51.7807|info|Thread(11): Block #61454: Received block has less signatures, re-transmitting local block. (total signatures: 11).
> 2018-11-22 06:43:51.7807|warn|Thread(11): Attempting to add a duplicate message (code: newBlock) to the normal priority network queue
> 2018-11-22 06:43:51.7827|info|Thread(11): Received block #61454 1513d3c68ffd687ea19120a7bc75220a64b1ce6bc99b7f9866472cb0f29b524a (12 sigs) from the network.
> 2018-11-22 06:43:51.7927|info|Thread(11): Estimated network hash rate is 17404771 H/s (previous was: 17222184 H/s). Difficulty adjusts from 18445574142902986121 -> 18445580279559166517.
> 2018-11-22 06:43:51.7977|info|Thread(27): Estimated network hash rate is 17404771 H/s (previous was: 17222184 H/s). Difficulty adjusts from 18445574142902986121 -> 18445580279559166517.
> 2018-11-22 06:43:51.7977|info|Thread(27): Creating a WalletState snapshot.
> 2018-11-22 06:43:51.8577|info|Thread(27): Reverting WalletState snapshot (11 wallets).
> 2018-11-22 06:43:51.8577|info|Thread(27): VerifyBlock duration: 71,2449ms
> 2018-11-22 06:43:51.8577|warn|Thread(27): Block sigFreeze verification failed for #61454. Checksum is 9d90fbf3abd5d261a3d8db1a926a54a2969f1fb09894c8f3c168b2426572cee5, but should be 422048b2a03d74bcaf661f729f32efc1d520262735347748dfe4052807b66209. Requesting block #61449
> 2018-11-22 06:43:51.8577|warn|Thread(27): Signature freeze checksum verification failed on current localNewBlock #61454, waiting for the correct target block.

**Comment by IxiAngel** [comment]
Hi!

Thanks for reporting the issue, we are currently working on it and we should have a fix ready today/tomorrow.
